# Generated by Django 4.1.2 on 2022-10-09 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=15, unique=True, verbose_name='CPF')),
                ('cidade', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cidade')),
                ('telefone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefone')),
                ('latitude', models.CharField(blank=True, max_length=50, null=True, verbose_name='Latitude')),
                ('longitude', models.CharField(blank=True, max_length=50, null=True, verbose_name='Longitude')),
                ('moedas', models.IntegerField(default=0, verbose_name='Moedinhas')),
                ('status', models.BooleanField(default=False, verbose_name='Ativado/Desativado')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Comunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da Comunidade')),
            ],
            options={
                'verbose_name': 'Comunidade',
                'verbose_name_plural': 'Comunidades',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Curso')),
                ('duracao', models.TimeField(verbose_name='Duração')),
                ('image', models.ImageField(upload_to='', verbose_name='Capa')),
                ('status', models.BooleanField(default=False, verbose_name='Ativado/Desativado')),
            ],
            options={
                'verbose_name': 'curso',
                'verbose_name_plural': 'cursos',
            },
        ),
        migrations.CreateModel(
            name='MeuNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negocios', related_query_name='negocio', to='user.cliente', verbose_name='Meu Negocio')),
            ],
            options={
                'verbose_name': 'Meu Negocio',
                'verbose_name_plural': 'Meus Negocios',
            },
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Valor')),
                ('criada_em', models.DateTimeField(verbose_name='Criada Em')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saida')], max_length=50, verbose_name='Tipo')),
                ('descricao', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descricao')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', related_query_name='transacao', to='user.meunegocio', verbose_name='Negocio')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
            },
        ),
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_estabelecimento', models.CharField(max_length=50, verbose_name='Nome do Estabelecimento')),
                ('numero_nota', models.CharField(max_length=50, verbose_name='Numero da Nota')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Valor')),
                ('data_geracao', models.DateTimeField(verbose_name='Data Geração')),
                ('url', models.URLField(max_length=500, verbose_name='Url')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_fiscais', related_query_name='nota_fiscal', to='user.cliente', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Nota Fiscal',
                'verbose_name_plural': 'Notas Fiscais',
            },
        ),
        migrations.CreateModel(
            name='MeuCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('FINALIZADO', 'Finalizado'), ('DISPONIVEL', 'Disponivel'), ('ANDAMENTO', 'Em Andamento')], max_length=15, verbose_name='Status')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.curso', verbose_name='Meus Cursos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', related_query_name='curso', to='user.cliente', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Meu Curso',
                'verbose_name_plural': 'Meus Cursos',
            },
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Valor Empréstimo')),
                ('parcelas', models.IntegerField(verbose_name='Parcelas')),
                ('quantas_pagas', models.IntegerField(blank=True, null=True, verbose_name='Quantas pagas')),
                ('finalizado', models.BooleanField(default=False, verbose_name='Finalizado')),
                ('data_criação', models.DateField(verbose_name='Data de Criação do Empréstimo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos', related_query_name='emprestimo', to='user.cliente', verbose_name='Colaborador')),
            ],
            options={
                'verbose_name': 'Empréstimo',
                'verbose_name_plural': 'Empréstimos',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='comunidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='user.comunidade', verbose_name='Comunidade'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
    ]
