# Generated by Django 4.1.2 on 2022-10-08 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_comunidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='vencimento',
        ),
    ]
