# Generated by Django 4.1.2 on 2022-10-08 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_emprestimo_vencimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Valor Emprestimo'),
        ),
    ]
