# Generated by Django 4.1.2 on 2022-10-08 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_emprestimo_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='moedas',
            field=models.IntegerField(default=0, verbose_name='Moedinhas'),
        ),
    ]
