# Generated by Django 4.1.2 on 2022-10-08 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_moedas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Curso')),
                ('duracao', models.TimeField(verbose_name='Duração')),
                ('image', models.ImageField(upload_to='', verbose_name='Capa')),
                ('status', models.BooleanField(default=False, verbose_name='Ativado/Desativado')),
            ],
            options={
                'verbose_name': 'curso',
                'verbose_name_plural': 'cursos',
            },
        ),
        migrations.CreateModel(
            name='MeuCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('FINALIZADO', 'Finalizado'), ('DISPONIVEL', 'Disponivel'), ('ANDAMENTO', 'Em Andamento')], max_length=15, verbose_name='Status')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.curso', verbose_name='Meus Cursos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', related_query_name='curso', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Meu Curso',
                'verbose_name_plural': 'Meus Cursos',
            },
        ),
    ]
