# Generated by Django 4.1.2 on 2022-10-08 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_curso_meucurso'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeuNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'MeuNegocio',
                'verbose_name_plural': 'MeuNegocios',
            },
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Valor')),
                ('criada_em', models.DateTimeField(verbose_name='Criada Em')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saida')], max_length=50, verbose_name='Tipo')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', related_query_name='transacao', to='user.meunegocio', verbose_name='Negocio')),
            ],
            options={
                'verbose_name': 'Transacao',
                'verbose_name_plural': 'Transacoes',
            },
        ),
    ]
