# Generated by Django 4.1.2 on 2022-10-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_meunegocio_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='descricao',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Descricao'),
        ),
    ]
