# Generated by Django 4.1.2 on 2022-10-08 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_transacao_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_estabelecimento', models.CharField(max_length=50, verbose_name='Nome do Estabelecimento')),
                ('numero_nota', models.CharField(max_length=50, verbose_name='Numero da Nota')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Valor')),
                ('data_geracao', models.DateTimeField(verbose_name='Data Geração')),
                ('url', models.URLField(max_length=500, verbose_name='Url')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_fiscais', related_query_name='nota_fiscal', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'NotaFiscal',
                'verbose_name_plural': 'NotaFiscals',
            },
        ),
    ]
